-- Polo © License | Discord : https://discord.gg/htfpJZN
peds = {
    { -- concess 
        id = "dealer",
        legal = true,
        ped = GetHashKey("a_f_y_femaleagent"),
        coords = vector3(-32.04, -1108.43, 25.42),
        heading = 165.41,
    },

    { -- Concess Sport
        id = "sports concessions",
        legal = true,
        ped = GetHashKey("a_f_y_femaleagent"),
        coords = vector3(-1182.06, -1719.25, 3.58),
        heading = 219.13,
    },

    { -- Concess Luxe
        id = "luxury concession ",
        legal = true,
        ped = GetHashKey("a_f_y_femaleagent"),
        coords = vector3(-789.41, -213.41, 36.07),
        heading = 119.66,
    },
    { -- Concess Truck
        id = "luxury concession",
        legal = true,
        ped = GetHashKey("a_f_y_femaleagent"),
        coords = vector3(1213.44, -1086.27, 38.66),
        heading = 219.00,
    },
    { -- Concess Motor Bike
        id = "motorcycle concession",
        legal = true,
        ped = GetHashKey("a_f_y_femaleagent"),
        coords = vector3(987.28, -145.68, 73.27),
        heading = 59.36,
    },
}
-- Polo © License | Discord : https://discord.gg/htfpJZN
mission = {
    {
        ped = "concessionaire",
        id = 1,
        type = "transport",
        Titre = "Transport of an 'Asea'",
        Desc = "We received a shipment from Asea, but we no longer have anyone to go there to get it. Can you take care of it?",
        LongText = "Great! Thank you for accepting. The Cargo has arrived, hurry up before it leaves for America ...! Pay attention and bring it back in 1 piece!",
        vehicule = GetHashKey("asea"),
        start = vector3(1215.06, -3030.45, 5.87),
        headingStart = 356.64,
        stop = vector3(-35.88, -1088.66, 26.42),
        prix = 230,
    },
    {
        ped = "concessionaire",
        id = 1,
        type = "transport",
        Titre = "Transport of an 'F620'",
        Desc = "We received a shipment of F620, but we no longer have anyone to go there to get it. Can you take care of it?",
        LongText = "Great ! Thank you for accepting. The Cargo has arrived, hurry up before it leaves for America ...! Pay attention and bring it back in 1 piece!",
        vehicule = GetHashKey("f620"),
        start = vector3(1215.06, -3030.45, 5.87),
        headingStart = 356.64,
        stop = vector3(-35.88, -1088.66, 26.42),
        prix = 230,
    },
    {
        ped = "concess",
        id = 1,
        type = "transport",
        Titre = "Transport of an 'Blista'",
        Desc = "We received a shipment of blista, but we no longer have anyone to go there to look. Can you take care of it? ",
        LongText = "Great ! Thank you for accepting. The Cargo has arrived, hurry before the competition arrives ...! Pay attention and bring it back in 1 piece! ",
        vehicule = GetHashKey("blista"),
        start = vector3(1215.06, -3030.45, 5.87),
        headingStart = 356.64,
        stop = vector3(-35.88, -1088.66, 26.42),
        prix = 230,
    },
    {
        ped = "sports concessions",
        id = 2,
        type = "transport",
        Titre = "Transport of an 'Bestia GTS'",
        Desc = "We received a shipment of Bestia GTS, but we no longer have anyone to go there to get it. Can you take care of it? ",
        LongText = "Great ! Thank you for accepting. The Cargo has arrived, hurry before the competition arrives ...! Pay attention and bring it back in 1 piece!",
        vehicule = GetHashKey("bestiagts"),
        start = vector3(1215.56, -3012.23, 5.86),
        headingStart = 0.25,
        stop = vector3(-1191.84, -1729.07, 4.58),
        prix = 230,
    },
    {
        ped = "sports concessions",
        id = 2,
        type = "transport",
        Titre = "Transport of an 'Comet'",
        Desc = "We received a cargo of 745le, but we no longer have anyone to go there to get it. Can you take care of it?",
        LongText = "Great ! Thank you for accepting. The Cargo has arrived, hurry up before it leaves for America ...! Pay attention and bring it back in 1 piece!",
        vehicule = GetHashKey("comet2")
        start = vector3(1215.56, -3012.23, 5.86),
        headingStart = 0.25,
        stop = vector3(-1191.84, -1729.07, 4.58),
        prix = 230,
    },
    {
        ped = "concessluxe",
        id = 2,
        type = "transport",
        Titre = "Transport of an '745le'",
        Desc = " We received a cargo of 745le, but we no longer have anyone to go there to get it. Can you take care of it?",
        LongText = "Great ! Thank you for accepting. The Cargo has arrived, hurry up before it leaves for America ...! Pay attention and bring it back in 1 piece!",
        vehicule = GetHashKey("745le"),
        start = vector3(1215.06, -3030.45, 5.87),
        headingStart = 356.64,
        stop = vector3(-772.65, -232.00, 37.07),
        prix = 230,
    },
    {
        ped = "concessluxe",
        id = 2,
        type = "transport",
        Titre = "Transport of an 'Cyclone'",
        Desc = "We received a shipment of Cyclone, but we no longer have anyone to go there to get it. Can you take care of it?",
        LongText = "Great ! Thank you for accepting. The Cargo has arrived, hurry before the competition arrives ...! Pay attention and bring it back in 1 piece!",
        vehicule = GetHashKey("cyclone"),
        start = vector3(1215.06, -3030.45, 5.87),
        headingStart = 356.64,
        stop = vector3(-772.65, -232.00, 37.07),
        prix = 230,
    },
    {
        ped = "concesstruck",
        id = 2,
        type = "transport",
        Titre = "Transport of an 'Baller'",
        Desc = "We received a shipment of Baller, but we no longer have anyone to go there and get it. Can you take care of it?",
        LongText = "Great ! Thank you for accepting. The Cargo has arrived, hurry before the competition arrives ...! Pay attention and bring it back in 1 piece!",
        vehicule = GetHashKey("baller2"),
        start = vector3(1215.56, -3012.23, 5.86),
        headingStart = 0.25,
        stop = vector3(1233.27, -1121.13, 39.33),
        prix = 230,
    },
    {
        ped = "concesstruck",
        id = 2,
        type = "transport",
        Titre = "Transport of an 'Blazer'",
        Desc = "We received a shipment of Blazer, but we no longer have anyone to go there to get it. Can you take care of it?",
        LongText = "Great ! Thank you for accepting. The Cargo has arrived, hurry before the competition arrives ...! Pay attention and bring it back in 1 piece!",
        vehicule = GetHashKey("blazer"),
        start = vector3(1215.56, -3012.23, 5.86),
        headingStart = 0.25,
        stop = vector3(1233.27, -1121.13, 39.33),
        prix = 230,
    },
    {
        ped = "concesstruck",
        id = 2,
        type = "transport",
        Titre = "Transport of an 'Dominator'",
        Desc = "We received a shipment from Dominator, but we no longer have anyone to go there and get it. Can you take care of it?",
        LongText = "Great ! Thank you for accepting. The Cargo has arrived, hurry before the competition arrives ...! Pay attention and bring it back in 1 piece!",
        vehicule = GetHashKey("dominator"),
        start = vector3(1215.56, -3012.23, 5.86),
        headingStart = 0.25,
        stop = vector3(1233.27, -1121.13, 39.33),
        prix = 230,
    },
    {
        ped = "concesstruck",
        id = 2,
        type = "transport",
        Titre = "Transport of an'Youga Luxuary'",
        Desc = "We received a shipment from Youga Luxuary, but we no longer have anyone to go there to get it. Can you take care of it?",
        LongText = "Great ! Thank you for accepting. The Cargo has arrived, hurry before the competition arrives ...! Pay attention and bring it back in 1 piece!",
        vehicule = GetHashKey("youga2"),
        start = vector3(1215.56, -3012.23, 5.86),
        headingStart = 0.25,
        stop = vector3(1233.27, -1121.13, 39.33),
        prix = 230,
    },
    {
        ped = "concessmotorbike",
        id = 2,
        type = "transport",
        Titre = "Transport of a 'Bati 801RR'",
        Desc = "We received a shipment of Bati 801RR, but we no longer have anyone to go there to get it. Can you take care of it?",
        LongText = "Great ! Thank you for accepting. The Cargo has arrived, hurry before the competition arrives ...! Pay attention and bring it back in 1 piece!",
        vehicule = GetHashKey("bati2"),
        start = vector3(1215.56, -3012.23, 5.86),
        headingStart = 0.25,
        stop = vector3(985.91, -138.44, 73.09),
        prix = 230,
    },
}

RegisterNetEvent("RS_MISSION:GetConfig")
AddEventHandler("RS_MISSION:GetConfig", function()
    TriggerClientEvent("RS_MISSION:GetConfig", source, peds, mission)
end)