-- Polo © License | Discord : https://discord.gg/htfpJZN
peds = {
    { -- concess 
        id = "concess",
        legal = true,
        ped = GetHashKey("a_f_y_femaleagent"),
        coords = vector3(-32.04, -1108.43, 25.42),
        heading = 165.41,
    },

    { -- Concess Sport
        id = "concesssports",
        legal = true,
        ped = GetHashKey("a_f_y_femaleagent"),
        coords = vector3(-1182.06, -1719.25, 3.58),
        heading = 219.13,
    },

    { -- Concess Luxe
        id = "concessluxe",
        legal = true,
        ped = GetHashKey("a_f_y_femaleagent"),
        coords = vector3(-789.41, -213.41, 36.07),
        heading = 119.66,
    },
    { -- Concess Truck
        id = "concesstruck",
        legal = true,
        ped = GetHashKey("a_f_y_femaleagent"),
        coords = vector3(1213.44, -1086.27, 38.66),
        heading = 219.00,
    },
    { -- Concess Motor Bike
        id = "concessmotorbike",
        legal = true,
        ped = GetHashKey("a_f_y_femaleagent"),
        coords = vector3(987.28, -145.68, 73.27),
        heading = 59.36,
    },
}
-- Polo © License | Discord : https://discord.gg/htfpJZN
mission = {
    {
        ped = "concess",
        id = 1,
        type = "transport",
        Titre = "Transport d'une 'Asea'",
        Desc = "On à reçue une cargaison de Asea, mais on à plus personne pour aller là chercher. Tu peux t'en occuper ?",
        LongText = "Super ! Merci d'avoir accepté. La Cargaison est arrivée, dêpeche toi avant quelle soit repartis en Amérique ... ! Fait attention et rapporte là en 1 seul morceaux!",
        vehicule = GetHashKey("asea"),
        start = vector3(1215.06, -3030.45, 5.87),
        headingStart = 356.64,
        stop = vector3(-35.88, -1088.66, 26.42),
        prix = 230,
    },
    {
        ped = "concess",
        id = 1,
        type = "transport",
        Titre = "Transport d'une 'F620'",
        Desc = "On à reçue une cargaison de F620, mais on à plus personne pour aller là chercher. Tu peux t'en occuper ?",
        LongText = "Super ! Merci d'avoir accepté. La Cargaison est arrivée, dêpeche toi avant quelle soit repartis en Amérique ... ! Fait attention et rapporte là en 1 seul morceaux!",
        vehicule = GetHashKey("f620"),
        start = vector3(1215.06, -3030.45, 5.87),
        headingStart = 356.64,
        stop = vector3(-35.88, -1088.66, 26.42),
        prix = 230,
    },
    {
        ped = "concess",
        id = 1,
        type = "transport",
        Titre = "Transport d'une 'Blista'",
        Desc = "On à reçue une cargaison de blista, mais on à plus personne pour aller là chercher. Tu peux t'en occuper ?",
        LongText = "Super ! Merci d'avoir accepté. La Cargaison est arrivée, dêpeche toi avant que la concurrence arrive ... ! Fait attention et rapporte là en 1 seul morceaux!",
        vehicule = GetHashKey("blista"),
        start = vector3(1215.06, -3030.45, 5.87),
        headingStart = 356.64,
        stop = vector3(-35.88, -1088.66, 26.42),
        prix = 230,
    },
    {
        ped = "concesssports",
        id = 2,
        type = "transport",
        Titre = "Transport d'une 'Bestia GTS'",
        Desc = "On à reçue une cargaison de Bestia GTS, mais on à plus personne pour aller là chercher. Tu peux t'en occuper ?",
        LongText = "Super ! Merci d'avoir accepté. La Cargaison est arrivée, dêpeche toi avant que la concurrence arrive ... ! Fait attention et rapporte là en 1 seul morceaux!",
        vehicule = GetHashKey("bestiagts"),
        start = vector3(1215.56, -3012.23, 5.86),
        headingStart = 0.25,
        stop = vector3(-1191.84, -1729.07, 4.58),
        prix = 230,
    },
    {
        ped = "concesssports",
        id = 2,
        type = "transport",
        Titre = "Transport d'une 'Comet'",
        Desc = "On à reçue une cargaison de 745le, mais on à plus personne pour aller là chercher. Tu peux t'en occuper ?",
        LongText = "Super ! Merci d'avoir accepté. La Cargaison est arrivée, dêpeche toi avant quelle soit repartis en Amérique ... ! Fait attention et rapporte là en 1 seul morceaux!",
        vehicule = GetHashKey("comet2"),
        start = vector3(1215.56, -3012.23, 5.86),
        headingStart = 0.25,
        stop = vector3(-1191.84, -1729.07, 4.58),
        prix = 230,
    },
    {
        ped = "concessluxe",
        id = 2,
        type = "transport",
        Titre = "Transport d'une '745le'",
        Desc = "On à reçue une cargaison de 745le, mais on à plus personne pour aller là chercher. Tu peux t'en occuper ?",
        LongText = "Super ! Merci d'avoir accepté. La Cargaison est arrivée, dêpeche toi avant quelle soit repartis en Amérique ... ! Fait attention et rapporte là en 1 seul morceaux!",
        vehicule = GetHashKey("745le"),
        start = vector3(1215.06, -3030.45, 5.87),
        headingStart = 356.64,
        stop = vector3(-772.65, -232.00, 37.07),
        prix = 230,
    },
    {
        ped = "concessluxe",
        id = 2,
        type = "transport",
        Titre = "Transport d'une 'Cyclone'",
        Desc = "On à reçue une cargaison de Cyclone, mais on à plus personne pour aller là chercher. Tu peux t'en occuper ?",
        LongText = "Super ! Merci d'avoir accepté. La Cargaison est arrivée, dêpeche toi avant que la concurrence arrive ... ! Fait attention et rapporte là en 1 seul morceaux!",
        vehicule = GetHashKey("cyclone"),
        start = vector3(1215.06, -3030.45, 5.87),
        headingStart = 356.64,
        stop = vector3(-772.65, -232.00, 37.07),
        prix = 230,
    },
    {
        ped = "concesstruck",
        id = 2,
        type = "transport",
        Titre = "Transport d'une 'Baller'",
        Desc = "On à reçue une cargaison de Baller, mais on à plus personne pour aller là chercher. Tu peux t'en occuper ?",
        LongText = "Super ! Merci d'avoir accepté. La Cargaison est arrivée, dêpeche toi avant que la concurrence arrive ... ! Fait attention et rapporte là en 1 seul morceaux!",
        vehicule = GetHashKey("baller2"),
        start = vector3(1215.56, -3012.23, 5.86),
        headingStart = 0.25,
        stop = vector3(1233.27, -1121.13, 39.33),
        prix = 230,
    },
    {
        ped = "concesstruck",
        id = 2,
        type = "transport",
        Titre = "Transport d'une 'Blazer'",
        Desc = "On à reçue une cargaison de Blazer, mais on à plus personne pour aller là chercher. Tu peux t'en occuper ?",
        LongText = "Super ! Merci d'avoir accepté. La Cargaison est arrivée, dêpeche toi avant que la concurrence arrive ... ! Fait attention et rapporte là en 1 seul morceaux!",
        vehicule = GetHashKey("blazer"),
        start = vector3(1215.56, -3012.23, 5.86),
        headingStart = 0.25,
        stop = vector3(1233.27, -1121.13, 39.33),
        prix = 230,
    },
    {
        ped = "concesstruck",
        id = 2,
        type = "transport",
        Titre = "Transport d'une 'Dominator'",
        Desc = "On à reçue une cargaison de Dominator, mais on à plus personne pour aller là chercher. Tu peux t'en occuper ?",
        LongText = "Super ! Merci d'avoir accepté. La Cargaison est arrivée, dêpeche toi avant que la concurrence arrive ... ! Fait attention et rapporte là en 1 seul morceaux!",
        vehicule = GetHashKey("dominator"),
        start = vector3(1215.56, -3012.23, 5.86),
        headingStart = 0.25,
        stop = vector3(1233.27, -1121.13, 39.33),
        prix = 230,
    },
    {
        ped = "concesstruck",
        id = 2,
        type = "transport",
        Titre = "Transport d'une 'Youga Luxuary'",
        Desc = "On à reçue une cargaison de Youga Luxuary, mais on à plus personne pour aller là chercher. Tu peux t'en occuper ?",
        LongText = "Super ! Merci d'avoir accepté. La Cargaison est arrivée, dêpeche toi avant que la concurrence arrive ... ! Fait attention et rapporte là en 1 seul morceaux!",
        vehicule = GetHashKey("youga2"),
        start = vector3(1215.56, -3012.23, 5.86),
        headingStart = 0.25,
        stop = vector3(1233.27, -1121.13, 39.33),
        prix = 230,
    },
    {
        ped = "concessmotorbike",
        id = 2,
        type = "transport",
        Titre = "Transport d'une 'Bati 801RR'",
        Desc = "On à reçue une cargaison de Bati 801RR, mais on à plus personne pour aller là chercher. Tu peux t'en occuper ?",
        LongText = "Super ! Merci d'avoir accepté. La Cargaison est arrivée, dêpeche toi avant que la concurrence arrive ... ! Fait attention et rapporte là en 1 seul morceaux!",
        vehicule = GetHashKey("bati2"),
        start = vector3(1215.56, -3012.23, 5.86),
        headingStart = 0.25,
        stop = vector3(985.91, -138.44, 73.09),
        prix = 230,
    },
}

RegisterNetEvent("RS_MISSION:GetConfig")
AddEventHandler("RS_MISSION:GetConfig", function()
    TriggerClientEvent("RS_MISSION:GetConfig", source, peds, mission)
end)